<a href="https://colab.research.google.com/github/cawilson503/Python/blob/main/Assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Question 1: Load the data from the link
https://files.zillowstatic.com/research/public_csvs/zhvi/Metro_zhvi_uc_sfrcondo_tier_0.33_0.67_sm_sa
_month.csv
• Open this file as a DataFrame in Pandas.
• Save the DataFrame, df_homes, to a local CSV file, “zillow_home_data.csv”.
• Load zillow_home_data.csv back into a new Dataframe, df_homes_2
• Compare the dimensions of the two DataFrames, df_homes and df_homes_2.
• Are df_homes and df_homes_2 equal? If not, how can you fix it?

In [ ]:
!jupyter nbconvert --to html Assignment4.ipynb

[NbConvertApp] Converting notebook Assignment4.ipynb to html
[NbConvertApp] Writing 785185 bytes to Assignment4.html

In [ ]:
#Q1#Q1
import pandas as pd

df = pd.read_csv('zillow.csv')
print(df)
df.to_csv('zillow_home_data.csv')
df_homes_2 = pd.read_csv('zillow_home_data.csv')

     RegionID  SizeRank       RegionName RegionType StateName     1/31/2000  \
0      102001         0    United States    country       NaN  115935.31590
1      394913         1     New York, NY        msa        NY  186046.30220
2      753899         2  Los Angeles, CA        msa        CA  227934.13140
3      394463         3      Chicago, IL        msa        IL  144602.58900
4      394514         4       Dallas, TX        msa        TX  131691.57890
..        ...       ...              ...        ...       ...           ...
890    753929       935       Zapata, TX        msa        TX           NaN
891    394743       936    Ketchikan, AK        msa        AK           NaN
892    753874       937        Craig, CO        msa        CO   94645.47165
893    395188       938       Vernon, TX        msa        TX           NaN
894    394767       939       Lamesa, TX        msa        TX           NaN

        2/29/2000     3/31/2000     4/30/2000     5/31/2000  ...  \
0    116139.21520  116391.92670  116933.82010  117557.34920  ...
1    186838.05200  187635.90740  189251.80500  190921.92100  ...
2    228777.23660  229903.72100  232164.56170  234644.88000  ...
3    144739.69300  144997.70430  145640.55910  146412.48040  ...
4    131757.47850  131831.95090  132018.25660  132256.26990  ...
..            ...           ...           ...           ...  ...
890           NaN           NaN           NaN           NaN  ...
891           NaN           NaN           NaN           NaN  ...
892   94885.73898   95335.34124   95975.67323   96719.74189  ...
893           NaN           NaN           NaN           NaN  ...
894           NaN           NaN           NaN           NaN  ...

        8/31/2022     9/30/2022    10/31/2022    11/30/2022    12/31/2022  \
0    347272.46690  346127.34160  345037.35560  344157.37630  343028.25590
1    594087.00430  592212.16580  590061.16080  588257.30760  585819.53200
2    930252.80210  924158.03830  918674.36150  914887.25440  910454.63930
3    299057.52810  297402.85080  296084.75300  295378.85510  294693.02880
4    390937.41950  388929.59790  386801.59080  384852.94450  382265.72430
..            ...           ...           ...           ...           ...
890   92392.94906   91072.05445   89603.92002   87772.76181   86549.58725
891  395585.94860  395777.11180  396064.32950  395691.64960  394254.53800
892  250841.89080  252157.41100  253789.55480  255343.63940  256686.69820
893   71325.14300   71398.85723   71233.01758   70629.82835   69492.07791
894   68048.17511   67563.02091   67500.67044   67120.83579   66827.14178

        1/31/2023     2/28/2023     3/31/2023     4/30/2023     5/31/2023
0    342370.40500  342313.07800  343511.42570  344671.16570  346269.73090
1    585784.41810  586990.91600  590868.12400  593926.37840  598030.64520
2    901932.51180  891572.67370  884109.08260  881866.90230  885563.79640
3    295277.54450  296365.75460  298300.11060  299645.40070  301406.05450
4    379628.60530  377490.73140  376750.93560  376403.54600  376816.77880
..            ...           ...           ...           ...           ...
890   88306.36076   91002.53639   94200.94576   95097.73047   95633.51308
891  392479.70350  391722.67160  392650.96010  394162.58320  395182.11970
892  257797.54230  259969.16040  263284.51950  267352.53500  271054.37740
893   70798.41867   72651.30385   75053.08799   75548.30550   75717.42399
894   69369.92387   71801.30802   73385.81645   71806.21843   70279.59037

[895 rows x 286 columns]

In [ ]:
print(df_homes_2)

     Unnamed: 0  RegionID  SizeRank       RegionName RegionType StateName  \
0             0    102001         0    United States    country       NaN
1             1    394913         1     New York, NY        msa        NY
2             2    753899         2  Los Angeles, CA        msa        CA
3             3    394463         3      Chicago, IL        msa        IL
4             4    394514         4       Dallas, TX        msa        TX
..          ...       ...       ...              ...        ...       ...
890         890    753929       935       Zapata, TX        msa        TX
891         891    394743       936    Ketchikan, AK        msa        AK
892         892    753874       937        Craig, CO        msa        CO
893         893    395188       938       Vernon, TX        msa        TX
894         894    394767       939       Lamesa, TX        msa        TX

        1/31/2000     2/29/2000     3/31/2000     4/30/2000  ...  \
0    115935.31590  116139.21520  116391.92670  116933.82010  ...
1    186046.30220  186838.05200  187635.90740  189251.80500  ...
2    227934.13140  228777.23660  229903.72100  232164.56170  ...
3    144602.58900  144739.69300  144997.70430  145640.55910  ...
4    131691.57890  131757.47850  131831.95090  132018.25660  ...
..            ...           ...           ...           ...  ...
890           NaN           NaN           NaN           NaN  ...
891           NaN           NaN           NaN           NaN  ...
892   94645.47165   94885.73898   95335.34124   95975.67323  ...
893           NaN           NaN           NaN           NaN  ...
894           NaN           NaN           NaN           NaN  ...

        8/31/2022     9/30/2022    10/31/2022    11/30/2022    12/31/2022  \
0    347272.46690  346127.34160  345037.35560  344157.37630  343028.25590
1    594087.00430  592212.16580  590061.16080  588257.30760  585819.53200
2    930252.80210  924158.03830  918674.36150  914887.25440  910454.63930
3    299057.52810  297402.85080  296084.75300  295378.85510  294693.02880
4    390937.41950  388929.59790  386801.59080  384852.94450  382265.72430
..            ...           ...           ...           ...           ...
890   92392.94906   91072.05445   89603.92002   87772.76181   86549.58725
891  395585.94860  395777.11180  396064.32950  395691.64960  394254.53800
892  250841.89080  252157.41100  253789.55480  255343.63940  256686.69820
893   71325.14300   71398.85723   71233.01758   70629.82835   69492.07791
894   68048.17511   67563.02091   67500.67044   67120.83579   66827.14178

        1/31/2023     2/28/2023     3/31/2023     4/30/2023     5/31/2023
0    342370.40500  342313.07800  343511.42570  344671.16570  346269.73090
1    585784.41810  586990.91600  590868.12400  593926.37840  598030.64520
2    901932.51180  891572.67370  884109.08260  881866.90230  885563.79640
3    295277.54450  296365.75460  298300.11060  299645.40070  301406.05450
4    379628.60530  377490.73140  376750.93560  376403.54600  376816.77880
..            ...           ...           ...           ...           ...
890   88306.36076   91002.53639   94200.94576   95097.73047   95633.51308
891  392479.70350  391722.67160  392650.96010  394162.58320  395182.11970
892  257797.54230  259969.16040  263284.51950  267352.53500  271054.37740
893   70798.41867   72651.30385   75053.08799   75548.30550   75717.42399
894   69369.92387   71801.30802   73385.81645   71806.21843   70279.59037

[895 rows x 287 columns]

In [ ]:
print(df.shape)

(895, 286)

In [ ]:
print(df_homes_2.shape)

(895, 287)

In [ ]:
print("The dimensions are not equal. The second saved dataframe has an additional column.")

The dimensions are not equal. The second saved dataframe has an additional column.

Question 2: Consider the following Python dictionary data and Python list labels:
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'] [5 Points]
1. Create a DataFrame df from this dictionary data which has the index labels.
2. Display a summary of the basic information about this DataFrame and its data (hint: there is a
single method that can be called on the DataFrame).
3. Return the first 3 rows of the DataFrame df
4. Select just the 'animal' and 'age' columns from the DataFrame df.
5. Select the data in rows [3, 4, 8] and in columns ['animal', 'age'].
6. Select the rows where the age is missing, i.e. it is NaN.
7. Select the rows where the animal is a cat and the age is less than 3.
8. Calculate the sum of all visits in df (i.e. the total number of visits).
9. Count the number of each type of animal in df.
10. In the 'animal' column, change the 'snake' entries to 'python'.

In [ ]:
#2
import pandas as pd
import numpy as np
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
'age': [2.5, 3, 0.5, 'np.nan', 5, 2, 4.5, 'np.nan', 7, 3],
'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)
print(df)

  animal     age  visits priority
a    cat     2.5       1      yes
b    cat       3       3      yes
c  snake     0.5       2       no
d    dog  np.nan       3      yes
e    dog       5       2       no
f    cat       2       3       no
g  snake     4.5       1       no
h    cat  np.nan       1      yes
i    dog       7       2       no
j    dog       3       1       no

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   animal    10 non-null     object
 1   age       10 non-null     object
 2   visits    10 non-null     int64
 3   priority  10 non-null     object
dtypes: int64(1), object(3)
memory usage: 400.0+ bytes
None

In [ ]:
print(df.loc['a':'c'])

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat    3       3      yes
c  snake  0.5       2       no

In [ ]:
print(df[['animal', 'age']])

  animal     age
a    cat     2.5
b    cat       3
c  snake     0.5
d    dog  np.nan
e    dog       5
f    cat       2
g  snake     4.5
h    cat  np.nan
i    dog       7
j    dog       3

In [ ]:
print(df.iloc[[3,4,8], 0:2])

  animal     age
d    dog  np.nan
e    dog       5
i    dog       7

In [ ]:
print(df.loc[df['age'] == 'np.nan'])

  animal     age  visits priority
d    dog  np.nan       3      yes
h    cat  np.nan       1      yes

In [ ]:
print(df['animal'].value_counts())

cat      4
dog      4
snake    2
Name: animal, dtype: int64

In [ ]:
print("Sum of visits:" ,df["visits"].sum())

Sum of visits: 19

In [ ]:
print(df.replace('snake', 'python'))

   animal     age  visits priority
a     cat     2.5       1      yes
b     cat       3       3      yes
c  python     0.5       2       no
d     dog  np.nan       3      yes
e     dog       5       2       no
f     cat       2       3       no
g  python     4.5       1       no
h     cat  np.nan       1      yes
i     dog       7       2       no
j     dog       3       1       no

In [ ]:
df.replace('np.nan', np.nan, inplace=True)
df.dropna(inplace=True)
df['age'] = df['age'].astype(float)
df = df[df['animal'] == 'cat']
df['age'] = df['age'].astype(float)
df = df[df['age'] < 3]
print(df)

  animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

<ipython-input-26-1983e3cfddff>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['age'] = df['age'].astype(float)

Question 3: Watch the video (https://www.youtube.com/watch?v=ZZPiWZpdekA)
and practice the exercise in your own notebook.
Link to the dataset

In [ ]:
#Import Necessary Libraries
import pandas as pd
#Import Dataset
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
df = pd.read_csv(url,sep = '\t')

In [ ]:
#assign to a variable called chipo
chipo = df

In [ ]:
chipo.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [ ]:
chipo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

In [ ]:
#How many products are more than $10
chipo ['price_float'] = pd.to_numeric(chipo.item_price.str.slice(1))

In [ ]:
(chipo ['price_float'] > 10).sum()

1130

In [ ]:
#Sort by item
chipo['price_per_item'] = chipo.price_float / chipo.quantity

In [ ]:
product_prices = chipo.groupby('item_name').agg({'price_per_item': 'max'})

In [ ]:
product_prices.head()

                       price_per_item
item_name
6 Pack Soft Drink                6.49
Barbacoa Bowl                   11.75
Barbacoa Burrito                11.75
Barbacoa Crispy Tacos           11.75
Barbacoa Salad Bowl             11.89

In [ ]:
(product_prices.price_per_item > 10).sum()

25

In [ ]:
product_prices

                                       price_per_item
item_name
6 Pack Soft Drink                                6.49
Barbacoa Bowl                                   11.75
Barbacoa Burrito                                11.75
Barbacoa Crispy Tacos                           11.75
Barbacoa Salad Bowl                             11.89
Barbacoa Soft Tacos                             11.75
Bottled Water                                    1.50
Bowl                                             7.40
Burrito                                          7.40
Canned Soda                                      1.09
Canned Soft Drink                                1.25
Carnitas Bowl                                   11.75
Carnitas Burrito                                11.75
Carnitas Crispy Tacos                           11.75
Carnitas Salad                                   8.99
Carnitas Salad Bowl                             11.89
Carnitas Soft Tacos                             11.75
Chicken Bowl                                    11.25
Chicken Burrito                                 11.25
Chicken Crispy Tacos                            11.25
Chicken Salad                                   10.98
Chicken Salad Bowl                              11.25
Chicken Soft Tacos                              11.25
Chips                                            2.15
Chips and Fresh Tomato Salsa                     2.95
Chips and Guacamole                              4.45
Chips and Mild Fresh Tomato Salsa                3.00
Chips and Roasted Chili Corn Salsa               2.95
Chips and Roasted Chili-Corn Salsa               2.39
Chips and Tomatillo Green Chili Salsa            2.95
Chips and Tomatillo Red Chili Salsa              2.95
Chips and Tomatillo-Green Chili Salsa            2.39
Chips and Tomatillo-Red Chili Salsa              2.39
Crispy Tacos                                     7.40
Izze                                             3.39
Nantucket Nectar                                 3.39
Salad                                            7.40
Side of Chips                                    1.69
Steak Bowl                                      11.75
Steak Burrito                                   11.75
Steak Crispy Tacos                              11.75
Steak Salad                                      8.99
Steak Salad Bowl                                11.89
Steak Soft Tacos                                11.75
Veggie Bowl                                     11.25
Veggie Burrito                                  11.25
Veggie Crispy Tacos                              8.49
Veggie Salad                                     8.49
Veggie Salad Bowl                               11.25
Veggie Soft Tacos                               11.25

In [ ]:
chipo[chipo.item_name == 'Chicken Bowl']

,order_id,quantity,item_name,choice_description,item_price,price_float,price_per_item
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98,16.98,8.49
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98,10.98,10.98
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25,11.25,11.25
19,10,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$8.75,8.75,8.75
26,13,1,Chicken Bowl,"[Roasted Chili Corn Salsa (Medium), [Pinto Bea...",$8.49,8.49,8.49
...,...,...,...,...,...,...,...
4590,1825,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$11.25,11.25,11.25
4591,1825,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",$8.75,8.75,8.75
4595,1826,1,Chicken Bowl,"[Tomatillo Green Chili Salsa, [Rice, Black Bea...",$8.75,8.75,8.75
4599,1827,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Cheese, Lettuce]]",$8.75,8.75,8.75
4604,1828,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$8.75,8.75,8.75

In [ ]:
#quantity of most expensive item ordered
chipo.price_float.idxmax()

3598

In [ ]:
chipo.loc[3598,:]

order_id                                      1443
quantity                                        15
item_name             Chips and Fresh Tomato Salsa
choice_description                             NaN
item_price                                 $44.25
price_float                                  44.25
price_per_item                                2.95
Name: 3598, dtype: object

In [ ]:
#how many times veggie salad bowl was ordered
chipo[chipo.item_name == 'Veggie Salad Bowl'].quantity.sum()

18

In [ ]:

#how many times more than one canned soda were orderd
(chipo[chipo.item_name == 'Canned Soda'].quantity > 1).sum()
(chipo[chipo.item_name == 'Canned Soda'].quantity > 1).count()

104

Question 4: Given a DataFrame of random numeric values: [5 Points]
df = pd.DataFrame(np.random.random(size=(5, 3))) # this is a 5x3 DataFrame
how do you subtract the row mean from each element in the row?
Hint: Use df.sub()

In [ ]:

import numpy as np
import pandas as pd

df = pd.DataFrame(np.random.random(size=(5,3)))
print(df)

          0         1         2
0  0.011973  0.554469  0.084079
1  0.827279  0.917195  0.011285
2  0.062103  0.076950  0.266500
3  0.952372  0.815786  0.976954
4  0.503173  0.674341  0.401007

In [ ]:
print(df.mean(axis=1))
new_df = (df.sub(df.mean(axis=1),axis=0)) #you have to use axis=1 to get mean of rows, and axis=0 to subtract each element, syntax is
#(other, axis='columns', level=None, fill_value=None)
print(new_df)

0    0.216840
1    0.585253
2    0.135184
3    0.915037
4    0.526174
dtype: float64
          0         1         2
0 -0.204868  0.337628 -0.132761
1  0.242026  0.331942 -0.573968
2 -0.073081 -0.058234  0.131316
3  0.037335 -0.099252  0.061917
4 -0.023001  0.148167 -0.125166

In [ ]:
print("You have to use axis=1 to get mean of rows, and axis=0 to subtract it from each element when using df.sub(), otherwise the number of" '\n'
"rows and columns will be incorrect.")

You have to use axis=1 to get mean of rows, and axis=0 to subtract it from each element when using df.sub(), otherwise the number of
rows and columns will be incorrect.

Question 5: Practice the “Practice Notebook” (uploaded in the Module Section) and submit it[5 Points]
Note: This is a Bonus Question
.

In [ ]:
import pandas as pd

In [ ]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

In [ ]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7])

In [ ]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

In [ ]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [ ]:
df2

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [ ]:
df3

      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [ ]:
pd.concat([df1,df2,df3])

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [ ]:
pd.concat([df1,df2,df3],axis=1)

      A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [ ]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})

right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})

In [ ]:
left

  key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [ ]:
right

  key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

___

In [ ]:
pd.merge(left,right,how='inner',on='key')

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [ ]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})

right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

In [ ]:
pd.merge(left, right, on=['key1', 'key2'])

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [ ]:
pd.merge(left, right, how='outer', on=['key1', 'key2'])

  key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K1   A3   B3  NaN  NaN
5   K2   K0  NaN  NaN   C3   D3

In [ ]:
pd.merge(left, right, how='right', on=['key1', 'key2'])

  key1 key2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K1   K0   A2   B2  C2  D2
3   K2   K0  NaN  NaN  C3  D3

In [ ]:
pd.merge(left, right, how='left', on=['key1', 'key2'])

  key1 key2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   K1  A3  B3  NaN  NaN

In [ ]:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2'])

right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])

In [ ]:
left.join(right)

     A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [ ]:
left.join(right, how='outer')

      A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3